language: python
python:
    - "3.6"
install:
    - pip install flake8
    - pip install Flask-WTF
    - pip install coveralls
script:
    - flake8 .

language: shell
script:
  - bash -c 'shopt -s globstar; shellcheck **/*.{sh,ksh,bash}'