language: "python"
python:
    - "2.7"
    - "3.5"
install:
    - pip install flake8
    - pip install Flask-WTF
    - pip install coveralls
script:
    - flake8 .
    - ./check_dos_format.sh # check if files has ^M (windows format)
