---
- name: Installs the latest git package
  hosts: all
  gather_facts: False

  tasks:

  - name: Verify Python is installed
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    become: yes
    become_user: root

  - setup:

  - name: Install git package
    package: name=git state=latest
    become: yes
    become_user: root

